services:
  web:
    build:
      context: ./web
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_started
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
    restart: unless-stopped

  scheduler:
    build:
      context: ./scheduler
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - app-net
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"

      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"
      ROUTER_COLLECTION: "routers"

      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_DEFAULT_PASS}"
    restart: unless-stopped

  worker:
    build:
      context: ./worker
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - app-net
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"

      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "ipa2026_db"

      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_PASSWORD: "${RABBITMQ_DEFAULT_PASS}"
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    restart: unless-stopped

volumes:
  mongo-data:
  rabbitmq-data:

networks:
  app-net:
    driver: bridge